### ISSUE TITLE
Hockeypuck crashes due to WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by mowirth** [hockeypuck/server#22]
Hi,

Hockeypuck crashes with this error message when using Hockeypuck and Conflux. I have about 50 peers so this may not happen with less peers - the crash occurs a few hours after starting. 

sync: WaitGroup is reused before previous Wait has returned
goroutine 225582 [running]:
sync.(*WaitGroup).Wait(0xc420086948)
/usr/lib/golang/src/sync/waitgroup.go:133 +0xbb
gopkg.in/hockeypuck/conflux.v2/recon.(*Peer).mutate.func1(0xc420086918, 0x9e3b18)
/opt/fks/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:216 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc420086918, 0xc420e70000)
/opt/fks/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
/opt/fks/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0xc0

**Comment by 4a6f656c** [comment]
The following PR should address this issue:

https://github.com/hockeypuck/conflux/pull/4
